version: '3.8'

services:
  web:
    build: .
    command: /home/app/web/entrypoint.sh
    volumes:
      - .:/home/app/web/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: 