# Generated by Django 4.2.19 on 2025-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_key',
            field=models.CharField(default='laptops', max_length=450),
        ),
    ]
