# Generated by Django 4.2.19 on 2025-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_product_search_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttrend',
            name='search_key',
            field=models.CharField(default='laptops', max_length=450),
        ),
    ]
