# Generated by Django 4.2.19 on 2025-02-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_producttrend_search_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='analyzer_pr_name_b0f7f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='analyzer_pr_price_a6f80c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='analyzer_pr_rating_698b27_idx',
        ),
    ]
